rainlab/translate-plugin

Plugin.php, lang/en/lang.php, lang/es/lang.php, lang/fr/lang.php, lang/hu/lang.php, lang/nl/lang.php, lang/pt-br/lang.php, lang/ru/lang.php
Adding proper permissions to plugin
=> Adding proper permissions + adding lang keys and messages

models/Message.php
It makes it easier to use the method inside Controllers and Components
=> Minor fix for trans method

controllers/locales/index.htm, controllers/messages/index.htm
Maybe the breadcrumb is unnecessary for the list pages.
=> Remove the breadcrumbs

controllers/locales/index.htm, controllers/messages/index.htm
Reverts rainlab/translate-plugin#142
Did not look nice otb
=> Revert "Remove the breadcrumbs"

Plugin.php
fix https://github.com/rainlab/translate-plugin/issues/143
=> make Plural translatable

Plugin.php
Issue URL: https://github.com/rainlab/translate-plugin/issues/215
=> Fixes translation not working with Partials loaded via AJAX

controllers/Messages.php, controllers/messages/_table_toolbar.htm, lang/en/lang.php
Added search feature to make it easier for users with lots of data to translate.
Thank you.
=> search feature

classes/LocaleMiddleware.php, updates/version.yaml
Fixes config reference as discussed here: https://github.com/rainlab/translate-plugin/pull/318
cc @LukeTowers @vannut
=> Fix config reference

config/config.php, models/Message.php
Using `Config` as per @LukeTowers advise.
=> Configurable cache timeout. Resolves #334

README.md, components/LocalePicker.php
Added an event which triggers on language switch to allow for parameter manipulation.
Credit to @mariavilaro, I added some documentation and cleaned it a bit, so we can get this merged ;-)
@LukeTowers
=> Translate URL parameters

models/MessageImport.php
As reported in https://github.com/rainlab/translate-plugin/issues/387
=> Fix import issue

formwidgets/MLMarkdownEditor.php, formwidgets/MLRepeater.php, formwidgets/MLRichEditor.php, formwidgets/mlmarkdowneditor/partials/_mlmarkdowneditor.htm, formwidgets/mlrepeater/partials/_mlrepeater.htm, formwidgets/mlricheditor/partials/_mlricheditor.htm, formwidgets/mltext/partials/_mltext.htm, formwidgets/mltextarea/partials/_mltextarea.htm, traits/MLControl.php
I made these changes in April and never committed them, can't remember if it worked or not. I feel like it did but no idea now.
=> Improve implementation of MLControl

README.md
Add a section the the documentation to show how use this plugin without JQuery and October frameworks css and js file
Related:
#425 #426
=> Documentation of hand-made request to change lang

models/Locale.php, updates/version.yaml
=> Fix replacement of `lists` to `pluck` -> array should be returned.

formwidgets/MLRepeater.php, formwidgets/mlrepeater/assets/js/mlrepeater.js
Related: https://github.com/octobercms/october/pull/4234
=> Bring MLRepeater inline with core changes to Repeater

classes/TranslatableBehavior.php
=> add getter for translatableOriginals array

Plugin.php
Fixes #113. Related: https://github.com/octobercms/october/commit/4f0b237aad2f0368770bd8e0822e645f527b1b05. Replaces https://github.com/rainlab/translate-plugin/pull/442
=> Make FileUpload properties translatable

behaviors/TranslatableModel.php
=> Add operator to where clause

behaviors/TranslatableCmsObject.php
=> delete translation static content when parent page is deleted

Plugin.php
=> Implement localeUrl filter

formwidgets/MLRepeater.php
Reference #481 
october:454
translate: 1.6.0
pages: 1.2.21
=> Fixes issue with indexing

formwidgets/MLRepeater.php
make sure $value is an array when using array_values
=> fix #482 issue

README.md
=> Improved readme for retrieving translated models value

Plugin.php
Reverts rainlab/translate-plugin#509
=> Revert "Prevent from duplicate extending"

lang/fr/lang.php
Added the few missing messages
=> French language file

behaviors/TranslatableCmsObject.php
Fixes #447
Page would not save if only placeholders content was added/modified.
=> add placeholders to isEmptyDataSet() verifications

README.md
=> Document the translate:scan artisan command

assets/js/multilingual.js
=> only call setLocale() if locale has changed

classes/ThemeScanner.php
e.g. `"My String" | _ | capitalize`
=> fix regex when "|_" filter is followed by another filter

classes/TranslatableBehavior.php
fix problem where translatableAttributes is not initialized when model is first loaded.
=> fix translatableAttributes

updates/builder_table_update_rainlab_translate_locales.php, updates/update_messages_table.php
dropColumn() should be called using Schema::table()
=> fix migration on down() method

assets/css/messages.css, assets/less/messages.less, controllers/messages/config_table.yaml
=> fix messages table layout on mobile

classes/TranslatableBehavior.php
=> Translate json fields

Plugin.php, behaviors/TranslatablePageUrl.php, classes/EventRegistry.php, controllers/locales/_update_form.htm
This adds the ability to translate CMS page properties using the October 2.0 Editor
=> Adds support for new Editor

assets/css/multilingual.css, assets/less/multilingual.less
=> Increase the lang button right margin

models/Locale.php
Hey, looks like this where is useless becase is_enabled is boolean then it can be removed.
=> Remove useless where

README.md
Reverts rainlab/translate-plugin#674
Fixes #705
=> Revert "Fix incorrect docs about content & mail template translation"

models/Attribute.php
This solves issue number 2) described here: https://github.com/octobercms/october-private/issues/615
=> Fix issue when duplication relation
