behaviors/TranslatableModel.php
Before, the fallback was useless. It was never called because `$this->translatableAttributes[$locale][$key]` is never unset but just empty.
=> Change check for translation in getTranslateAttribute

.gitignore, composer.json, models/Message.php, phpunit.xml, tests/functional/models/MessageTest.php, tests/unit/models/MessageTest.php
This PR fixes #82. I have created it based on an assumption that the message codes are merely used as a key of the hash table of messages. If I have overlooked anything, hashing may not be the way to solve the unicode message issue. Anyway, I need unicode messages to be translatable in my current project and I have tested and confirmed it working great with unicode messages as well as the English based ones.
The message code is replaced by a hash value using [MurmurHash 3](https://github.com/lastguest/murmurhash-php), the [fastest non-cryptographic hashing algorithm](https://github.com/Cyan4973/xxHash#benchmarks) I can find without the need of an extension, yet has a fairly well collision avoidance. (Extended reading: [Hash functions: An empirical …
=> Fixed unicode message not translatable

traits/mlcontrol/partials/_locale_values.htm
If this is not done, laravels escaping helper function `e` will through an error
> "htmlentities() expects parameter 1 to be string, array given" on line 469 of /vendor/laravel/framework/src/Illuminate/Support/helpers.php
=> Set value to an empty string if empty

routes.php
When upgrading to Laravel 5.5 I got an error when visiting the homepage in a foreign locale: "Session store not set on request." Adding the "web" middleware to one remaining route fixed it.
I believe this was just an oversight in this commit: https://github.com/rainlab/translate-plugin/commit/aa6e523dbe47c60e6ee318e3a7e1a32d7ca52db8
=> Add missing web middleware

behaviors/TranslatableModel.php
When updating a model, the storeTranslatableIndexData is called. Inside the foreach loop, if any of the attributes are empty strings, on line 151, it returns and drops out. If the next attribute is not empty, and needs to be updated, it fails. Changing this to a continue resolves this. 
Don't believe I'm missing anything but if there's a better solution or a reason for the return, happy to change!
Thanks, 
James
=> storeTranslatableIndexData returning within a loop

formwidgets/mltext/partials/_mltext.htm
I moved this change to its own branch, please close #199 
This is a small change that allows to define a maxlength attribute for a multilanguage text field
=> Support maxlength attribute

classes/TranslatableBehavior.php
When using the method hasTranslation() we need to make sure that the translatableData has been loaded, just like in a few other methods, otherwise an undefined index will halt execution.
@see https://github.com/rainlab/translate-plugin/issues/302
=> Ensure that translatableData has been loaded in hasTranslation()

classes/ThemeScanner.php
Adding method to scan translatable messages into email templates. See: https://github.com/rainlab/translate-plugin/issues/87. It depends: https://github.com/octobercms/october/pull/3152
=> Adding method to scan translatable messages into email templates

lang/nl/lang.php
Updates Dutch ( `/lang/nl/lang.php` ) file. Iterates on #233 and adds the other missing translation keys that have been added since.
Preferably needs a check by another Dutchie.
=> Update Dutch (NL) language file

Plugin.php, classes/Translator.php, components/AlternateHrefLangElements.php, components/LocalePicker.php, components/alternatehreflangelements/default.htm, config/config.php, lang/en/lang.php, lang/nl/lang.php
This PR adds two things to the translate plugin:
1 - A component which renders alt hreflang elements 
2 - adds a setting to ask if we need to prefix the default locale
According to [Google's locale recommendations](https://support.google.com/webmasters/answer/189077) we need to inject alternative languages in the head of a website as following:
```html
<link rel="alternate" hreflang="en" href="/en" />
<link rel="alternate" hreflang="nl" href="/nl" />
```
This needs to be done for _every_ language including the current language.
When creating this component, the fact I didn't want to have the default locale prefixed, issue #315 regarding the behaviour when redirecting to the default locale and PR #317 let me to alter the behaviour of the forceurl redirect-method, the second part of this PR …
=> PrefixDefaultLocale setting and Alt hreflang element

classes/LocaleMiddleware.php, updates/version.yaml
With regards of [this issue](https://github.com/rainlab/translate-plugin/pull/318#issuecomment-354567683) this PR will add a check for the prefixDefaultLocale setting into the middleware.
As a result the said wrong behaviour will disappear :)
Thanks @msimkunas for speeding up the debugging a lot 👍
=>  Update middleware to use prefixDefaultLocale 

components/LocalePicker.php, updates/version.yaml
should fix https://github.com/rainlab/translate-plugin/issues/336
=> preserve query string, when switching locales

behaviors/TranslatableModel.php
Add operator option for TransWhere function, with default option being '='.
Most likely use of this new option is to use "LIKE" operator instead of an equal value.
In order to use it, the locale variable will need to have either a locale value or `null`.
=> Add operator option for TransWhere function

models/MessageImport.php
When importing translated messages, default language (denoted by x) is currently overwritten with codes. Example:
Before import:
- Code = test.message 
- Default = Test Message
After import:
- Code = test.message
- Default = **test.message**
This PR fixes that issue, so that only translations are imported. Default language (usually coming directly from the template source code) is not changed.
=> Fix issue where default texts are overwritten by import

assets/css/multilingual.css, assets/less/multilingual.less
A PR to fix the position of the language switcher for translatable repeaters.
See following issue for more details:
https://github.com/rainlab/translate-plugin/issues/401
=> PR: Fix position of the language switcher menu to remove UI overlap.

models/Message.php
Quite specific case. At a certain event of one user, the letter is sent to another user and this letter can be in different languages ​​depending on what the second user has set in the profile. If the message was sent to one user, then it went to the other in the same language regardless of the specified locale.
=> fix Message's cache

README.md
Added explanation to README.md how to make default translation added in theme.yaml effective. I had to dig into the source code to figure it out. I wonder why no one has asked about this, though.
=> Explain how to make default translation effective

assets/js/multilingual.js
=> fix ctrl-click opening  new tab on firefox

models/Locale.php
In Locale model lists() is used, but it's deprecated since Laravel 5.3
=> Locale model: lists deprecated, pluck instead

behaviors/TranslatablePage.php, classes/TranslatableBehavior.php, tests/fixtures/classes/TranslatablePage.php, tests/unit/behaviors/TranslatablePageTest.php, updates/version.yaml
The TranslatableBehavior class prevents the getter/setter for "translatable" dynamic property to work when hooking to the model.beforeGetAttribute / model.beforeSetAttribute events.
This PR fix the issue by ignoring the hook when the key == 'translatable"
=> fix translatable behavior event hooks

formwidgets/MLRepeater.php
Due to a recent change in https://github.com/octobercms/library, changing the $_POST superglobal directly doesn't work any more. 
The issue is described more in detail here: https://github.com/octobercms/library/commit/fd839047c2d7757f225a8ed60673ca8a20fe7df4
=> Fix post value rewrite

assets/js/multilingual.js
This change handle the new 'oc.inputPreset.beforeUpdate' event triggered by OctoberCMS core in modules/system/assets/ui/js/input.preset.js
ref. https://github.com/octobercms/october/pull/4217
=> Handle oc.inputPreset.beforeUpdate event

classes/EventRegistry.php
Repeater and NestedForm formwidgets' field names are marked as translatable when they should when their name matches another field name from the model.
Fix #459
=> prevent nested field names from matching Model->translatable[] fields

behaviors/TranslatablePage.php
I extend CMS Page translatable attributes with custom SEO fields like `og_title`,  `og_description`.
Before this change I get array access error when to try create new CMS Page. The value of `$this->translatableOriginals[$key]`does not exists for key `og_title`.
After change the error does not appear and everything works as expected. I just check if value for the key exists, if so then it will return value for that key the same as before and if not `array_get` function will return `null`.
=> Fix array error when extending CMS Page original translatable attributes

behaviors/TranslatableModel.php
Hello,
I've lately come across an undesired behaviour with blog plugin (https://github.com/rainlab/blog-plugin/issues/299). As I've explained in the issue, the field content_html is "computed" from the content field in the beforeSave function and the translated value **does not get updated**.
This, however, is true only if you don't use the original MLBlogMarkdown control because it currently has the logic of computing content_html field implemented internally. 
I've tried to come up with the most reasonable solution and my best implementation so far would be to fire an event, before saving translation data, that can provide computed values which then would be added to the translated attributes array.
The counterpart to this implementation in subclasses of Model would look like this:
``` …
```
=> Add ability for models to provide computed data

config/config.php, routes.php
New config to disable locale prefix routes (disableLocalePrefixRoutes). Defaults to false.
Resolves #476
=> add option to disable locale prefix routes

README.md, classes/ThemeScanner.php
Resolves #262 
Allow specifying a yaml file PER LOCALE in theme.yaml "translate" section. e.g.:
```
translate:
en: lang-en.yaml
fr: lang-fr.yaml
```
credit: @hocopor
=> Per locale translate configs

Plugin.php
While flushing model event listeners in `PluginTestCase.php` the plugin throws an exception that the class has already been extended. 
This fix will prevent the class from trying to extend it twice.
All in all, does anybody know why extending the class twice throws Exception instead of ignoring it and proceeding? :)
=> Prevent from duplicate extending

behaviors/TranslatableModel.php, models/Attribute.php, tests/unit/behaviors/TranslatableModelTest.php
TranslatableBehavior with a "translations" morphMany relation to the new Attribute model, so you can use the Eloquent eager loading, for example:
```php
public function scopeList($query)
{
return $query->with([
'translations',
'featured_image',
'featured_image.translations',
]);
}
```
=> Attribute model and translations morphMany relation

Plugin.php
make sure the translatable property gets added even if a plugin with higher precedence added it first
=> properly add translatable propertyto extended model

behaviors/TranslatablePage.php, classes/TranslatableBehavior.php
since the hook to the "model.beforeGetAttribute" event is returning a value, the model accessors/mutators were not triggered anymore.
fixes #353
=> restore support for accessors & mutators

Plugin.php, console/ScanCommand.php
This is useful for automated website deployment.
(Typically I will include this command in my deploy script for updating translations in case of a theme update).
The command is equivalent to the backend GUI.
Usage:
`php artisan translate:scan`
or for purging old messages first:
`php artisan translate:scan --purge`
=> Add console command for scanning messages

behaviors/TranslatablePage.php
Adds explicit parentheses on nested ternary operators for PHP 7.4 support
https://www.php.net/manual/en/migration74.deprecated.php#migration74.deprecated.core.nested-ternary
=> Fixes "Unparenthesized `a ? b : c ? d : e` is deprecated"

updates/migrate_morphed_indexes.php, updates/version.yaml
As discussed with @daftspunk via Slack.
This adds a migration to migrate existing `rainlab_translate_indexes` values to use any registered morph map alises. 
This is the same problem that was already fixed in the `rainlab_translate_attributes` table in the previous version.
=> 1.6.7: Introduce migration to patch existing indexes using morph map

Plugin.php, README.md
Fields are not marked as translatable by default.
It is a theme author responsibility to configure required fields via theme's config and mark fields as `translatable`.
For example:
```
tabs:
fields:
####################################################
####################################################
website_name:
tab: Info
label: Website Name
type: text
default: Octaskin
translatable: true
```
And the result is:
=> Fix for rainlab/translate-plugin#376

Plugin.php, assets/css/messages.css, assets/css/multilingual.css, assets/less/multilingual.less
- add registerBundle() calls to allow compiling LESS files into CSS
- make sure multi-lingual input form controls have padding-right of 44px
=> Register asset bundle

assets/js/messages.js, classes/ThemeScanner.php, controllers/Messages.php, controllers/messages/_scan_messages_form.htm, controllers/messages/_table_headers.htm, controllers/messages/config_table.yaml, controllers/messages/index.htm, lang/en/lang.php, models/Message.php, updates/update_messages_table.php, updates/version.yaml
Related bug report: #525 
I've added another checkbox in the scanner window that when checked will purge only the messages that the scanner was unable to find. For the life of me I couldn't figure out how to add a column to the list view to indicate that the string couldn't be found in the project anymore to give the translator an idea which strings can be safely deleted.
~~It is also missing a migration to add a `boolean` column to `rainlab_translate_messages` called `found`. I'm not exactly sure how that should be handled since you need to increment the version.~~
=> Add option to purge only deleted messages

README.md
Just spent a good hour trying to figure out why the translate key wasn't outputting the translated text. The translate key must be in quotes when calling it inside the translate twig filter. 👍
=> Fix docs: translate key missing quotes

updates/version.yaml
Warn users about the Message::trans() breaking changes (introduced in #554)
=> Add breaking change warning

README.md, classes/ThemeScanner.php
Fired events in ThemeScanner.php class for ability to  extend scan method.
=> Fired events in the theme scanner.

models/MessageExport.php, models/MessageImport.php, tests/unit/models/ExportMessageTest.php, tests/unit/models/ImportMessageTest.php
Fixes #422 
Reworked original PR from few years ago #431
=> Allows to export default locale

models/Message.php
If there is a Message translations for "en" locale and current locale (or requested locale) is "en-us", return translation for "en" before returning fallback translation.
=> try locale without country before returning default translation

classes/TranslatableBehavior.php, traits/MLControl.php
Complements https://github.com/rainlab/pages-plugin/pull/445
- changes the MenuItem title/url fields to MLText formwidget
- handle the `pages.menu.referencesGenerated` event to replace MenuItem title/url with their translation (if available)
=> Add support for translating RainLab.Pages MenuItem properties

assets/css/multilingual.css, assets/less/multilingual.less
the previously introduced change was overlapping with other input fields when the textarea did not have a label on top.
=> Restore multilingual button position for textarea

classes/MLContent.php, models/MessageImport.php, tests/unit/behaviors/TranslatableModelTest.php, tests/unit/behaviors/TranslatablePageTest.php, updates/builder_table_update_rainlab_translate_locales.php, updates/update_messages_table.php
fixes https://github.com/rainlab/pages-plugin/issues/453
update migration files with incorrect syntax
=> add missing allowedExtensions in MLContent

Plugin.php, README.md, classes/EventRegistry.php
=> mail templates/views can now be localized

behaviors/TranslatableModel.php
This PR is an alternative version of https://github.com/rainlab/translate-plugin/pull/586
Instead of creating a separate method that has a different behavior to the original implementation, I managed to fix ``transWhere`` itself by utilizing 2 queries instead of the slow orWhere clause. This implementation also preserves the fallback functionality.
I made some tests on my project (originally discussed here: https://github.com/rainlab/translate-plugin/issues/581) - now I have 2 queries that execute in ~ 5 ms instead of a single 60 second query. The improvement is significant.
Comments are welcome.
=> Faster version of transWhere

models/Message.php
Change calling protected method makeCacheKey and makeMessageCode with static, to enable call override method from custom Message class.
example:
class Message extends \RainLab\Translate\Models\Message
{
/**
* @param string $messageId
* @return string
*/
protected static function makeMessageCode($messageId)
{
return $messageId;
}
}
=> Change self::makeCacheKey and self::makeMessageCode to static::

classes/TranslatableBehavior.php
adding withFallbackLocale to inverse noFallbackLocale.
Useful when iteration over multiple locales and reuse the model.
```php
// Translated locale links
if (class_exists('RainLab\Translate\Behaviors\TranslatableModel')) {
$currentLocale = (\RainLab\Translate\Classes\Translator::instance())->getLocale();
$translations = [];
foreach (\RainLab\Translate\Models\Locale::listEnabled() as $code => $locale) {
if($currentLocale === $code) continue;
$post->noFallbackLocale()->lang($code);
if (empty($post->title) || empty($post->slug) ) continue;
$post->translateContext($code);
if (!$category) {
$category = $post->categories->first();
}
$category->translateContext($code);
$translations[$code] =  [
'code' => $code,
'name' => $locale,
'slug' => $post->slug,
'url' => …
```
=> Adding noFallbackLocale inverse method

behaviors/TranslatableModel.php
This change gives an opportunity  of doing something before rainlab_translate_attributes are deleted
=> rainlab_translate_attributes deletion on afterDelete

README.md
The suffix is supposed to start with `-`, not `.`
https://github.com/rainlab/translate-plugin/blob/master/classes/EventRegistry.php#L394
=> Fix incorrect docs about content & mail template translation

classes/ThemeScanner.php
In a parent/child theme setup, the parent theme nevers gets scanned for messages, except when the child theme supplies an invalid configuration (like non-existant file or syntax error in the YAML file - something that throws an exception).
This PR lets scanThemeConfigForMessagesInternal return false if no configuration value is present,
so the part of ThemeScanner.php that handles parent theme translations can check for false and try the parent theme.
If a translate config key is present in the child, only the child configuration gets used, as intended.
=> Fix for parent theme not getting scanned for messages, except when the child theme configuration throws an exception

behaviors/TranslatableModel.php
This PR attempts to solve the issue of using ``transWhereNoFallback`` in the default locale. In that case, we don't want to query translatable indexes, since we store the default locale in the main table.
Further discussion: https://github.com/rainlab/translate-plugin/pull/623
=> Handle default locale in transWhereNoFallback

classes/EventRegistry.php
Fixed error ``SystemException: The partial '_field_mltext' is not found`` when opening Pages->Menus.
Translations in Page plugin of course don't work yet, but with this PR it is at least possible to edit the default language.
=> Remove mltext reference

classes/EventPluginRegistry.php
If we have a custom repeater on a Page, each item gets a ``viewBag[url]`` text field added. This PR prevents that from happening.
=> Do not add translatable fields to nested widgets

classes/ThemeScanner.php
I believe this is needed if we want to add custom messages to the scanner:
```php
Event::listen('rainlab.translate.themeScanner.afterScan', function(ThemeScanner $scanner) {
$scanner->importMessages(['Custom message 1', 'Custom message 2']);
});
```
=> Make importMessages public

classes/Locale.php
This fixes issue #734 , allowing the plugins to change the Site context to send an email, generate a pdf, etc in a language different than the current one:
```
$siteId = Site::listEnabled()->where('locale', $newLocale)->first()->id;
Site::withContext($siteId, function () use ($sendTo, $template) {
Mail::sendTo($sendTo, $template);
});
```
=> Use Site context to get the current site
